# Generated by Django 3.0.5 on 2020-05-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_api', '0002_auto_20200307_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster_url',
            field=models.URLField(default='https://cutt.ly/DyPhP2N'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(to='users_api.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
