# Generated by Django 3.0.5 on 2020-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_auto_20200524_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='games',
            field=models.ManyToManyField(blank=True, to='users_api.Game'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='games',
            field=models.ManyToManyField(blank=True, to='users_api.Game'),
        ),
    ]
